add login step for gcp-build

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -271,9 +271,9 @@ jobs:
 
       # ✅ Authenticate FIRST
       - name: Authenticate to GCP
-        uses: google-github-actions/auth@v2
+        uses: google-github-actions/auth@v3
         with:
-         credentials_json: ${{ secrets.GCP_SA_KEY }}
+         credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
 
       - name: Fix gcloud install location
         run: |
@@ -1233,6 +1233,35 @@ jobs:
           kubectl apply -f ingress-gcp.yaml 
           kubectl apply -f service-gcp.yaml  
           
+      - name: Login ArgoCD
+        shell: bash
+        run: |
+         set -euo pipefail
+
+         kubectl -n argocd port-forward svc/argocd-server 8080:443 >/tmp/argocd-pf.log 2>&1 &
+         PF_PID=$!
+
+         # cleanup only after the step finishes
+         trap 'kill "$PF_PID" >/dev/null 2>&1 || true' EXIT
+
+         # wait until port-forward is actually ready
+         for i in {1..60}; do
+         if curl -kfsS https://127.0.0.1:8080/ >/dev/null 2>&1; then
+         echo "Port-forward ready"
+         break
+         fi
+         if ! kill -0 "$PF_PID" >/dev/null 2>&1; then
+         echo "kubectl port-forward died. Logs:"
+         cat /tmp/argocd-pf.log || true
+         exit 1
+         fi
+         sleep 1
+         done
+
+         ARGO_PWD="$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)"
+         echo "ARGOCD_ADMIN_PASSWORD=$ARGO_PWD" >> "$GITHUB_ENV"
+
+         argocd login 127.0.0.1:8080 --username admin --password "$ARGO_PWD" --insecure 
           
       - name: Clean up runner (safe)
         if: always()
