edit Action

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -744,17 +744,7 @@ jobs:
       
 
           
-      - name: Install Helm
-        shell: bash
-        run: |
-         set -euo pipefail
-
-         HELM_VERSION="v3.14.4"
-         curl -fsSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm.tar.gz
-         tar -zxvf helm.tar.gz
-         sudo mv linux-amd64/helm /usr/local/bin/helm
-          helm version
-          
+      
       #   Detect VPC ID
       - name: Fetch VPC ID
         run: |
@@ -780,22 +770,22 @@ jobs:
           --cluster $AWS_CLUSTER_NAME \
           --approve    
        
-      - name: AWS Cloudformation Setup for ALB Controller
-        run: |
-          aws cloudformation describe-stack-events \
-          --stack-name eksctl-multi-cloud-cluster-addon-iamserviceaccount-kube-system-aws-load-balancer-controller \
-          --max-items 20
+      # - name: AWS Cloudformation Setup for ALB Controller
+      #   run: |
+      #     aws cloudformation describe-stack-events \
+      #     --stack-name eksctl-multi-cloud-cluster-addon-iamserviceaccount-kube-system-aws-load-balancer-controller \
+      #     --max-items 20
 
-      - name: Configure kubectl for EKS
-        shell: bash
-        run: |
-         set -euo pipefail
-         aws sts get-caller-identity
-         aws eks update-kubeconfig \
-         --region "$AWS_REGION" \
-         --name "$AWS_CLUSTER_NAME"
-         kubectl config current-context
-         kubectl get ns
+      # - name: Configure kubectl for EKS
+      #   shell: bash
+      #   run: |
+      #    set -euo pipefail
+      #    aws sts get-caller-identity
+      #    aws eks update-kubeconfig \
+      #    --region "$AWS_REGION" \
+      #    --name "$AWS_CLUSTER_NAME"
+      #    kubectl config current-context
+      #    kubectl get ns
 
       - name: Ensure IAM policy exists and capture ARN
         shell: bash
@@ -825,60 +815,99 @@ jobs:
          fi
 
           echo "ALB_POLICY_ARN=$POLICY_ARN" >> "$GITHUB_ENV"
+      
+
+      - name: Create/Update IRSA ServiceAccount (ALB Controller)
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          SA="aws-load-balancer-controller"
+          NS="kube-system"
+
+          # Make sure kubeconfig works for eksctl + kubectl
+          aws eks update-kubeconfig --region "$AWS_REGION" --name "$AWS_CLUSTER_NAME"
+
+          # Create or update IRSA role + ServiceAccount in one go
+          eksctl create iamserviceaccount \
+          --cluster "$AWS_CLUSTER_NAME" \
+          --region "$AWS_REGION" \
+          --namespace "$NS" \
+          --name "$SA" \
+          --attach-policy-arn "$ALB_POLICY_ARN" \
+          --role-name "eks-alb-controller-role" \
+          --override-existing-serviceaccounts \
+          --approve
+
+          # Verify annotation
+          kubectl -n "$NS" get sa "$SA" \
+          -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}{"\n"}'      
 
 
-      - name: Ensure IRSA ServiceAccount for AWS Load Balancer Controller
+      - name: Install Helm
         shell: bash
         run: |
          set -euo pipefail
 
-         STACK="eksctl-${AWS_CLUSTER_NAME}-addon-iamserviceaccount-kube-system-aws-load-balancer-controller"
-         SA="aws-load-balancer-controller"
-         NS="kube-system"
+         HELM_VERSION="v3.14.4"
+         curl -fsSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm.tar.gz
+         tar -zxvf helm.tar.gz
+         sudo mv linux-amd64/helm /usr/local/bin/helm
+          helm version
+          
 
-         echo "Ensuring kube-system namespace exists..."
-         kubectl get ns "$NS" >/dev/null 2>&1 || kubectl create ns "$NS"
+      # - name: Ensure IRSA ServiceAccount for AWS Load Balancer Controller
+      #   shell: bash
+      #   run: |
+      #    set -euo pipefail
 
-         echo "Checking if ServiceAccount already exists..."
-         if kubectl -n "$NS" get sa "$SA" >/dev/null 2>&1; then
-         echo "✅ ServiceAccount exists already."
-         kubectl -n "$NS" get sa "$SA" -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}{"\n"}'
-         exit 0
-         fi
+      #    STACK="eksctl-${AWS_CLUSTER_NAME}-addon-iamserviceaccount-kube-system-aws-load-balancer-controller"
+      #    SA="aws-load-balancer-controller"
+      #    NS="kube-system"
 
-         echo "ServiceAccount missing. Discovering IRSA role from CloudFormation stack resources: $STACK"
+      #    echo "Ensuring kube-system namespace exists..."
+      #    kubectl get ns "$NS" >/dev/null 2>&1 || kubectl create ns "$NS"
 
-         ROLE_NAME="$(aws cloudformation list-stack-resources \
-         --stack-name "$STACK" \
-         --query "StackResourceSummaries[?ResourceType=='AWS::IAM::Role'].PhysicalResourceId | [0]" \
-         --output text)"
+      #    echo "Checking if ServiceAccount already exists..."
+      #    if kubectl -n "$NS" get sa "$SA" >/dev/null 2>&1; then
+      #    echo "✅ ServiceAccount exists already."
+      #    kubectl -n "$NS" get sa "$SA" -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}{"\n"}'
+      #    exit 0
+      #    fi
 
-         if [ -z "$ROLE_NAME" ] || [ "$ROLE_NAME" = "None" ]; then
-         echo "❌ Could not find IAM Role resource in stack. Showing resources for debugging:"
-         aws cloudformation list-stack-resources --stack-name "$STACK" --output table
-         exit 1
-         fi
+      #    echo "ServiceAccount missing. Discovering IRSA role from CloudFormation stack resources: $STACK"
 
-         ROLE_ARN="$(aws iam get-role \
-         --role-name "$ROLE_NAME" \
-         --query "Role.Arn" \
-         --output text)"
+      #    ROLE_NAME="$(aws cloudformation list-stack-resources \
+      #    --stack-name "$STACK" \
+      #    --query "StackResourceSummaries[?ResourceType=='AWS::IAM::Role'].PhysicalResourceId | [0]" \
+      #    --output text)"
 
-         echo "✅ Using IRSA role: $ROLE_ARN"
+      #    if [ -z "$ROLE_NAME" ] || [ "$ROLE_NAME" = "None" ]; then
+      #    echo "❌ Could not find IAM Role resource in stack. Showing resources for debugging:"
+      #    aws cloudformation list-stack-resources --stack-name "$STACK" --output table
+      #    exit 1
+      #    fi
 
-         kubectl apply -f - <<EOF
-         apiVersion: v1
-         kind: ServiceAccount
-         metadata:
-           name: ${SA}
-           namespace: ${NS}
-           annotations:
-            eks.amazonaws.com/role-arn: ${ROLE_ARN}
-         EOF
+      #    ROLE_ARN="$(aws iam get-role \
+      #    --role-name "$ROLE_NAME" \
+      #    --query "Role.Arn" \
+      #    --output text)"
 
-         echo "Verifying ServiceAccount exists..."
-         kubectl -n "$NS" get sa "$SA" -o yaml
-         kubectl -n "$NS" get sa "$SA" -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}{"\n"}'
+      #    echo "✅ Using IRSA role: $ROLE_ARN"
+
+      #    kubectl apply -f - <<EOF
+      #    apiVersion: v1
+      #    kind: ServiceAccount
+      #    metadata:
+      #      name: ${SA}
+      #      namespace: ${NS}
+      #      annotations:
+      #       eks.amazonaws.com/role-arn: ${ROLE_ARN}
+      #    EOF
+
+      #    echo "Verifying ServiceAccount exists..."
+      #    kubectl -n "$NS" get sa "$SA" -o yaml
+      #    kubectl -n "$NS" get sa "$SA" -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}{"\n"}'
 
 
       
@@ -892,11 +921,11 @@ jobs:
          -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}{"\n"}'
 
 
-      - name: Verify IAM Role Annotation
-        shell: bash
-        run: |
-         set -euo pipefail
-         kubectl -n kube-system get sa aws-load-balancer-controller -o yaml | grep "eks.amazonaws.com/role"   
+      # - name: Verify IAM Role Annotation
+      #   shell: bash
+      #   run: |
+      #    set -euo pipefail
+      #    kubectl -n kube-system get sa aws-load-balancer-controller -o yaml | grep "eks.amazonaws.com/role"   
 
       - name: Debug service account
         if: failure()
