edit aws jobs to self hosted runner

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -10,14 +10,14 @@ permissions:
 
 env:
   IMAGE_NAME: flask-app
- 
 
 jobs:
   # ----------------------------------------
   # 1️⃣ AWS JOB
   # ----------------------------------------
   aws-build-push:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux, vpc-runner]
+    environment: production
 
     env:
       AWS_REGION: ${{ secrets.AWS_REGION }}
@@ -69,7 +69,7 @@ jobs:
             -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
           kubectl apply \
             -f https://raw.githubusercontent.com/argoproj/argo-rollouts/stable/manifests/install.yaml
-          kubectl wait --for=condition=ready pod -n argocd --all --timeout=180s 
+          kubectl wait --for=condition=ready pod -n argocd --all --timeout=180s
 
       # Update gitop branch
       - name: Update AWS rollout manifests
@@ -93,9 +93,9 @@ jobs:
           else
             echo "No changes to commit"
           fi
-#
 
-       # ----------------------------------------
+        # ----------------------------------------
+      #
       # 🚨 SLACK NOTIFICATION FOR AWS JOB
       # ----------------------------------------
       - name: Slack Notify AWS Job
@@ -112,8 +112,8 @@ jobs:
             --data "{
               \"text\": \"*$JOB* finished with status: *$STATUS*\nRepo: $REPO\nCommit: $COMMIT\"
             }" \
-            $SLACK_WEBHOOK_URL    
-    #       
+            $SLACK_WEBHOOK_URL
+    #
 
   # ----------------------------------------
   # 2️⃣ GCP JOB
@@ -123,7 +123,10 @@ jobs:
     # needs: aws-build-push   # wait for AWS job to finish before starting GCP job
     strategy:
       matrix:
-        cluster: ['multi-cloud-cluster-cbd5a22291','my-gcp-cluster-254f3996a459'] # edit this list with your GKE cluster names
+        cluster: [
+            "multi-cloud-cluster-cbd5a22291",
+            "my-gcp-cluster-254f3996a459",
+          ] # edit this list with your GKE cluster names
 
     env:
       GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
@@ -154,7 +157,7 @@ jobs:
         with:
           cluster_name: ${{ matrix.cluster }}
           location: europe-west1
-          project_id: ${{ env.GCP_PROJECT_ID }}    
+          project_id: ${{ env.GCP_PROJECT_ID }}
 
       - name: Install gke auth plugin
         run: |
@@ -177,24 +180,22 @@ jobs:
              echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json --quiet
 
-       #  Clean and reconfigure Docker auth for Artifact Registry
+        #  Clean and reconfigure Docker auth for Artifact Registry
       - name: Clean old Docker logins (optional safeguard)
         run: |
-          docker logout https://europe-west1-docker.pkg.dev || true   
-          
-     
+          docker logout https://europe-west1-docker.pkg.dev || true
+
       - name: Docker login to GCP Artifact Registry
         run: |
           docker logout https://europe-west1-docker.pkg.dev || true
-          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet      
-      
+          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
 
-       # ✅ (Optional fallback: Manual login if gcloud helper fails)
+        # ✅ (Optional fallback: Manual login if gcloud helper fails)
       - name: Fallback Docker login (only if needed)
         if: failure()
         run: |
-         gcloud auth print-access-token | \
-         docker login -u oauth2accesstoken --password-stdin https://europe-west1-docker.pkg.dev 
+          gcloud auth print-access-token | \
+          docker login -u oauth2accesstoken --password-stdin https://europe-west1-docker.pkg.dev
 
       # Build Docker Image
       - name: Build GCP Image
@@ -222,7 +223,6 @@ jobs:
             -f https://raw.githubusercontent.com/argoproj/argo-rollouts/stable/manifests/install.yaml
           kubectl wait --for=condition=ready pod -n argocd --all --timeout=180s
 
-
       # Update gitop branch
       - name: Update GCP rollout manifests
         run: |
@@ -242,8 +242,7 @@ jobs:
           git commit -m "Update GCP rollout image $GITHUB_SHA" || true
           git push origin gitop || true
 
-
-       # ----------------------------------------
+        # ----------------------------------------
       # 🚨 SLACK NOTIFICATION FOR GCP JOB
       # ----------------------------------------
       - name: Slack Notify GCP Job
@@ -260,42 +259,38 @@ jobs:
             --data "{
               \"text\": \"*$JOB* finished with status: *$STATUS*\nRepo: $REPO\nCommit: $COMMIT\"
             }" \
-            $SLACK_WEBHOOK_URL    
-
-
-
+            $SLACK_WEBHOOK_URL
 
 #############################################################################################
 
 # Below steps to use if you do not want to use ArgoCD for deployment
 #############################################################################################
 
-   ##### if step 8 is used, skeep step 9 and vice versa #####
-       # 8️⃣ Deploy to GKE
-      # - name: Deploy to GKE
-      #   run: |
-      #     git fetch origin gitop
-      #     git checkout gitop
-      #     kubectl apply -f k8s/flask-app/deployment-gcp.yaml
-            # kubectl apply -f k8s/service.yaml
-            # kubectl apply -f k8s/ingress-gcp.yaml
-            # kubectl apply -f k8s/secret-gcp.yaml
+##### if step 8 is used, skeep step 9 and vice versa #####
+# 8️⃣ Deploy to GKE
+# - name: Deploy to GKE
+#   run: |
+#     git fetch origin gitop
+#     git checkout gitop
+#     kubectl apply -f k8s/flask-app/deployment-gcp.yaml
+# kubectl apply -f k8s/service.yaml
+# kubectl apply -f k8s/ingress-gcp.yaml
+# kubectl apply -f k8s/secret-gcp.yaml
 
-      # # Deploy to AWS Eks
-      # - name: Deploy to AWS EKS
-      #   env:
-      #     AWS_REGION: ${{ env.AWS_REGION }}
-      #     CLUSTER_NAME:  multi-cloud-cluster # replace with your EKS cluster name
-      #   run: |
-      #     # Update kubeconfig for EKS
-      #      git fetch origin gitop
-      #      git checkout gitop
-      #      aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
-      #      kubectl apply -f k8s/flask-app/deployment-aws.yaml
-           # kubectl apply -f k8s/service.yaml
-           # kubectl apply -f k8s/ingress-aws.yaml
-           # kubectl apply -f k8s/secret-aws.yaml
+# # Deploy to AWS Eks
+# - name: Deploy to AWS EKS
+#   env:
+#     AWS_REGION: ${{ env.AWS_REGION }}
+#     CLUSTER_NAME:  multi-cloud-cluster # replace with your EKS cluster name
+#   run: |
+#     # Update kubeconfig for EKS
+#      git fetch origin gitop
+#      git checkout gitop
+#      aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
+#      kubectl apply -f k8s/flask-app/deployment-aws.yaml
+# kubectl apply -f k8s/service.yaml
+# kubectl apply -f k8s/ingress-aws.yaml
+# kubectl apply -f k8s/secret-aws.yaml
 
-
-
-      ##### end of alternative steps #####
+##### end of alternative steps #####
+#
